// <auto-generated />
using System;
using GR.UserPreferences.Impl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GR.UserPreferences.Impl.Migrations
{
    [DbContext(typeof(UserPreferencesDbContext))]
    partial class UserPreferencesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GR.UserPreferences.Abstractions.Models.UserPreference", b =>
                {
                    b.Property<string>("Key");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Value");

                    b.HasKey("Key", "UserId");

                    b.ToTable("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
