stages:
  - test
  - deploy_to_server
  - deploy_to_nuget

cache:
  paths:
    - src/GR.WebHosts/GR.Cms/wwwroot/lib/
test_projects:
  stage: test
  script:
    - dotnet clean
    - dotnet build ./GR.sln
    - dotnet test ./src/GR.Tests/GR.Core.Tests/GR.Core.Tests.csproj

deploy_to_server_job:
  stage: deploy_to_server
  only:
    - develop
  environment:
    name: APP
  before_script:
    - pushd "./src/GR.WebHosts/GR.Cms"
    - dotnet restore
  script:
    - dotnet publish -c Release -o ./dist

deploy_to_nuget_job:
  stage: deploy_to_nuget
  only: 
    - master
  before_script:
    - pushd "./src"
  script:
    - ./deploy-packages.bat