// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ST.Entities.Data;

namespace ST.Entities.Migrations
{
    [DbContext(typeof(EntitiesDbContext))]
    [Migration("20190402132006_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Entities")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ST.Audit.Models.TrackAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DatabaseContextName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid>("RecordId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("TrackEventType");

                    b.Property<string>("TypeFullName");

                    b.Property<string>("UserName");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("TrackAudits");
                });

            modelBuilder.Entity("ST.Audit.Models.TrackAuditDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("PropertyName");

                    b.Property<string>("PropertyType");

                    b.Property<Guid?>("TenantId");

                    b.Property<Guid>("TrackAuditId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("TrackAuditId");

                    b.ToTable("TrackAuditDetails");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Attrs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("FieldId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Key");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("RowId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Type");

                    b.Property<string>("Value");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("RowId");

                    b.ToTable("Attrs");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassName");

                    b.Property<Guid>("ConfigId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("FormId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("RowId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("FormId");

                    b.HasIndex("RowId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.ColumnField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<Guid>("ColumnId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("FieldId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("Order");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("ColumnFields");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Editable");

                    b.Property<bool>("Fieldset");

                    b.Property<bool>("HideLabel");

                    b.Property<bool>("InputGroup");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Label");

                    b.Property<string>("Legend");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.DisabledAttr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<Guid>("ConfigId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("DisabledAttrs");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<Guid?>("ColumnId");

                    b.Property<Guid>("ConfigId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<string>("FMap");

                    b.Property<Guid>("FormId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("MetaId");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("Order");

                    b.Property<Guid?>("TableFieldId");

                    b.Property<string>("Tag");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("FormId");

                    b.HasIndex("MetaId");

                    b.HasIndex("TableFieldId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<string>("PostUrl");

                    b.Property<string>("RedirectUrl");

                    b.Property<Guid>("SettingsId");

                    b.Property<Guid>("TableId");

                    b.Property<Guid?>("TenantId");

                    b.Property<Guid>("TypeId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.HasIndex("TableId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TypeId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.FormFieldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<int>("Event");

                    b.Property<Guid>("FieldId");

                    b.Property<string>("Handler")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FormFieldEvents");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.FormType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("Code")
                        .HasColumnType("char(4)");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("FormTypes");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Group");

                    b.Property<string>("Icon");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassName");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("FieldId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Label");

                    b.Property<string>("ModifiedBy");

                    b.Property<bool>("Selected");

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("TypeLabel");

                    b.Property<string>("TypeValue");

                    b.Property<string>("Value");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Row", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<Guid>("ConfigId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("FormId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("StageId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("FormId");

                    b.HasIndex("StageId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.RowColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<Guid>("ColumnId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid>("RowId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("RowColumns");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("FormId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid?>("SettingsId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("SettingsId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.StageRows", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid>("RowId");

                    b.Property<Guid>("StageId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("StageRows");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<Guid>("BlockCategoryId");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CssCode");

                    b.Property<string>("Description");

                    b.Property<string>("FaIcon");

                    b.Property<string>("HtmlCode");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TableModelId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("BlockCategoryId");

                    b.HasIndex("TableModelId");

                    b.HasIndex("TenantId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.BlockAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<Guid>("BlockId");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DefaultValue");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Value");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("BlockAttributes");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.BlockCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BlockCategories");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsLayout");

                    b.Property<bool>("IsSystem");

                    b.Property<Guid?>("LayoutId");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid>("PageTypeId");

                    b.Property<string>("Path");

                    b.Property<Guid?>("SettingsId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.HasIndex("PageTypeId");

                    b.HasIndex("SettingsId");

                    b.HasIndex("TenantId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("Order");

                    b.Property<Guid>("PageId");

                    b.Property<string>("Script");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageScripts");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CssCode");

                    b.Property<string>("Description");

                    b.Property<string>("HtmlCode");

                    b.Property<string>("Icon");

                    b.Property<string>("Identifier");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("JsCode");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Title");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("PageSettings");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("Order");

                    b.Property<Guid>("PageId");

                    b.Property<string>("Script");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageStyles");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("PageTypes");
                });

            modelBuilder.Entity("ST.Entities.Models.RenderTemplates.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("IdentifierName")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Value");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("MachineName");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldConfigValues", b =>
                {
                    b.Property<Guid>("TableModelFieldId");

                    b.Property<Guid>("TableFieldConfigId");

                    b.Property<string>("Value");

                    b.HasKey("TableModelFieldId", "TableFieldConfigId");

                    b.HasIndex("TableFieldConfigId");

                    b.ToTable("TableFieldConfigValues");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldConfigs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasColumnType("char(4)");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid>("TableFieldTypeId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TableFieldTypeId");

                    b.ToTable("TableFieldConfigs");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("GroupName");

                    b.HasKey("Id");

                    b.ToTable("TableFieldGroups");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasColumnType("char(2)");

                    b.Property<string>("DataType");

                    b.Property<string>("Name");

                    b.Property<Guid>("TableFieldGroupsId");

                    b.HasKey("Id");

                    b.HasIndex("TableFieldGroupsId");

                    b.ToTable("TableFieldTypes");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("EntityType");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPartOfDbContext");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableModelFields", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowNull");

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DataType");

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<bool>("Synchronized");

                    b.Property<Guid>("TableFieldTypeId");

                    b.Property<Guid>("TableId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("TableFieldTypeId");

                    b.HasIndex("TableId");

                    b.HasIndex("TenantId");

                    b.ToTable("TableFields");
                });

            modelBuilder.Entity("ST.Entities.Models.ViewModels.ViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid>("TableModelId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("TableModelId");

                    b.HasIndex("TenantId");

                    b.ToTable("ViewModels");
                });

            modelBuilder.Entity("ST.Entities.Models.ViewModels.ViewModelFields", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<Guid?>("TableModelFieldsId");

                    b.Property<string>("Template");

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Translate");

                    b.Property<int>("Version");

                    b.Property<Guid>("ViewModelId");

                    b.HasKey("Id");

                    b.HasIndex("TableModelFieldsId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ViewModelId");

                    b.ToTable("ViewModelFields");
                });

            modelBuilder.Entity("ST.Audit.Models.TrackAuditDetails", b =>
                {
                    b.HasOne("ST.Audit.Models.TrackAudit")
                        .WithMany("AuditDetailses")
                        .HasForeignKey("TrackAuditId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Attrs", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Field", "Field")
                        .WithMany("Attrs")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Row", "Row")
                        .WithMany("Attrs")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Column", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Config", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Form")
                        .WithMany("Columns")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Row")
                        .WithMany("Columns")
                        .HasForeignKey("RowId");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.DisabledAttr", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Config")
                        .WithMany("DisabledAttrs")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Field", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Column")
                        .WithMany("Fields")
                        .HasForeignKey("ColumnId");

                    b.HasOne("ST.Entities.Models.Forms.Config", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Tables.TableModelFields", "TableField")
                        .WithMany()
                        .HasForeignKey("TableFieldId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Form", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Tables.TableModel", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.FormType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.FormFieldEvent", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Field", "Field")
                        .WithMany("FieldEvents")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Option", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Field")
                        .WithMany("Options")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Row", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Config", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Form")
                        .WithMany("Rows")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Stage")
                        .WithMany("Rows")
                        .HasForeignKey("StageId");
                });

            modelBuilder.Entity("ST.Entities.Models.Forms.Stage", b =>
                {
                    b.HasOne("ST.Entities.Models.Forms.Form")
                        .WithMany("Stages")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Forms.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.Block", b =>
                {
                    b.HasOne("ST.Entities.Models.Pages.BlockCategory", "BlockCategory")
                        .WithMany()
                        .HasForeignKey("BlockCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Tables.TableModel", "TableModel")
                        .WithMany()
                        .HasForeignKey("TableModelId");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.BlockAttribute", b =>
                {
                    b.HasOne("ST.Entities.Models.Pages.Block")
                        .WithMany("Attributes")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.Page", b =>
                {
                    b.HasOne("ST.Entities.Models.Pages.Page", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId");

                    b.HasOne("ST.Entities.Models.Pages.PageType", "PageType")
                        .WithMany()
                        .HasForeignKey("PageTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Pages.PageSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId");
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageScript", b =>
                {
                    b.HasOne("ST.Entities.Models.Pages.Page")
                        .WithMany("PageScripts")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Pages.PageStyle", b =>
                {
                    b.HasOne("ST.Entities.Models.Pages.Page")
                        .WithMany("PageStyles")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldConfigValues", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableFieldConfigs", "TableFieldConfig")
                        .WithMany()
                        .HasForeignKey("TableFieldConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.Entities.Models.Tables.TableModelFields", "TableModelField")
                        .WithMany("TableFieldConfigValues")
                        .HasForeignKey("TableModelFieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldConfigs", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableFieldTypes", "TableFieldType")
                        .WithMany("TableFieldConfigs")
                        .HasForeignKey("TableFieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableFieldTypes", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableFieldGroups", "TableFieldGroups")
                        .WithMany("TableFieldTypes")
                        .HasForeignKey("TableFieldGroupsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.Tables.TableModelFields", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableFieldTypes", "TableFieldType")
                        .WithMany()
                        .HasForeignKey("TableFieldTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ST.Entities.Models.Tables.TableModel", "Table")
                        .WithMany("TableFields")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.ViewModels.ViewModel", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableModel", "TableModel")
                        .WithMany()
                        .HasForeignKey("TableModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ST.Entities.Models.ViewModels.ViewModelFields", b =>
                {
                    b.HasOne("ST.Entities.Models.Tables.TableModelFields", "TableModelFields")
                        .WithMany()
                        .HasForeignKey("TableModelFieldsId");

                    b.HasOne("ST.Entities.Models.ViewModels.ViewModel")
                        .WithMany("ViewModelFields")
                        .HasForeignKey("ViewModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
