// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using GR.Dashboard.Data;

namespace GR.Dashboard.Migrations
{
    [DbContext(typeof(DashBoardDbContext))]
    [Migration("20190923093304_DashBoardDbContext_Add_Multiple_Dashboards")]
    partial class DashBoardDbContext_Add_Multiple_Dashboards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DashBoard")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GR.Audit.Abstractions.Models.TrackAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DatabaseContextName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<Guid>("RecordId");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("TrackEventType");

                    b.Property<string>("TypeFullName");

                    b.Property<string>("UserName");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("TrackAudits");
                });

            modelBuilder.Entity("GR.Audit.Abstractions.Models.TrackAuditDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("PropertyName");

                    b.Property<string>("PropertyType");

                    b.Property<Guid?>("TenantId");

                    b.Property<Guid>("TrackAuditId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("TrackAuditId");

                    b.ToTable("TrackAuditDetails");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.CustomWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCache");

                    b.Property<string>("Author");

                    b.Property<string>("BackGroundColor");

                    b.Property<int>("BorderRadius");

                    b.Property<string>("BorderStyle");

                    b.Property<TimeSpan>("CacheRefreshSpan");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassAttribute");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastRefreshTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid>("RowId");

                    b.Property<string>("Template")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<Guid>("WidgetGroupId");

                    b.Property<int>("WidgetTemplateType");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("WidgetGroupId");

                    b.ToTable("CustomWidgets");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.DashBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.Row", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("DashboardId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("WidgetGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43d52663-e6d9-4d39-aeff-fd8743cbcce1"),
                            Changed = new DateTime(2019, 9, 23, 9, 33, 3, 694, DateTimeKind.Utc).AddTicks(6443),
                            Created = new DateTime(2019, 9, 23, 9, 33, 3, 694, DateTimeKind.Utc).AddTicks(5876),
                            IsDeleted = false,
                            Name = "Charts",
                            Order = 1,
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("3e4d679b-c3a9-4c3d-9b2a-f054583cf8d0"),
                            Changed = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8227),
                            Created = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8220),
                            IsDeleted = false,
                            Name = "Reports",
                            Order = 2,
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("c0a787e3-5cb6-4e6e-b652-601167b251de"),
                            Changed = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8565),
                            Created = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8565),
                            IsDeleted = false,
                            Name = "Custom",
                            Order = 3,
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("79422e99-5fd4-402f-9a38-6c80c436dbad"),
                            Changed = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8599),
                            Created = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8598),
                            IsDeleted = false,
                            Name = "Samples",
                            Order = 4,
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("28bbb537-2303-4cbb-a5d6-f2df6f2e214f"),
                            Changed = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8617),
                            Created = new DateTime(2019, 9, 23, 9, 33, 3, 717, DateTimeKind.Utc).AddTicks(8617),
                            IsDeleted = false,
                            Name = "Custom",
                            Order = 5,
                            Version = 0
                        });
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ChartWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCache");

                    b.Property<string>("Author");

                    b.Property<string>("BackGroundColor");

                    b.Property<int>("BorderRadius");

                    b.Property<string>("BorderStyle");

                    b.Property<TimeSpan>("CacheRefreshSpan");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassAttribute");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastRefreshTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid>("RowId");

                    b.Property<string>("Template")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<Guid>("WidgetGroupId");

                    b.Property<int>("WidgetTemplateType");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("WidgetGroupId");

                    b.ToTable("ChartWidgets");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ListWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCache");

                    b.Property<string>("Author");

                    b.Property<string>("BackGroundColor");

                    b.Property<int>("BorderRadius");

                    b.Property<string>("BorderStyle");

                    b.Property<TimeSpan>("CacheRefreshSpan");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassAttribute");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastRefreshTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid>("RowId");

                    b.Property<string>("Template")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<Guid>("WidgetGroupId");

                    b.Property<int>("WidgetTemplateType");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("WidgetGroupId");

                    b.ToTable("ListWidgets");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ReportWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCache");

                    b.Property<string>("Author");

                    b.Property<string>("BackGroundColor");

                    b.Property<int>("BorderRadius");

                    b.Property<string>("BorderStyle");

                    b.Property<TimeSpan>("CacheRefreshSpan");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassAttribute");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastRefreshTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid>("RowId");

                    b.Property<string>("Template")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<Guid>("WidgetGroupId");

                    b.Property<int>("WidgetTemplateType");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("WidgetGroupId");

                    b.ToTable("ReportWidgets");
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.TabbedWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCache");

                    b.Property<string>("Author");

                    b.Property<string>("BackGroundColor");

                    b.Property<int>("BorderRadius");

                    b.Property<string>("BorderStyle");

                    b.Property<TimeSpan>("CacheRefreshSpan");

                    b.Property<DateTime>("Changed");

                    b.Property<string>("ClassAttribute");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastRefreshTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<Guid>("RowId");

                    b.Property<string>("Template")
                        .IsRequired();

                    b.Property<Guid?>("TenantId");

                    b.Property<int>("Version");

                    b.Property<Guid>("WidgetGroupId");

                    b.Property<int>("WidgetTemplateType");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("WidgetGroupId");

                    b.ToTable("TabbedWidgets");
                });

            modelBuilder.Entity("GR.Audit.Abstractions.Models.TrackAuditDetails", b =>
                {
                    b.HasOne("GR.Audit.Abstractions.Models.TrackAudit")
                        .WithMany("AuditDetailses")
                        .HasForeignKey("TrackAuditId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.CustomWidget", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.Row", "Row")
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GR.Dashboard.Abstractions.Models.WidgetGroup", "WidgetGroup")
                        .WithMany()
                        .HasForeignKey("WidgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.Row", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.DashBoard", "DashBoard")
                        .WithMany("Rows")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ChartWidget", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.Row", "Row")
                        .WithMany("ChartWidgets")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GR.Dashboard.Abstractions.Models.WidgetGroup", "WidgetGroup")
                        .WithMany()
                        .HasForeignKey("WidgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ListWidget", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.Row", "Row")
                        .WithMany("ListWidgets")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GR.Dashboard.Abstractions.Models.WidgetGroup", "WidgetGroup")
                        .WithMany()
                        .HasForeignKey("WidgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.ReportWidget", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.Row", "Row")
                        .WithMany("ReportWidgets")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GR.Dashboard.Abstractions.Models.WidgetGroup", "WidgetGroup")
                        .WithMany()
                        .HasForeignKey("WidgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GR.Dashboard.Abstractions.Models.WidgetTypes.TabbedWidget", b =>
                {
                    b.HasOne("GR.Dashboard.Abstractions.Models.Row", "Row")
                        .WithMany("TabbedWidgets")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GR.Dashboard.Abstractions.Models.WidgetGroup", "WidgetGroup")
                        .WithMany()
                        .HasForeignKey("WidgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
